version: '3.2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - dev
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
  php:
    image: opsbears/php-fpm:7.2
    networks:
      - dev
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
networks:
  dev:
    driver: bridge